- hosts: all
  tasks:
  - package: 
      name: "httpd"
 
  - copy:
      dest: "/var/www/html/index.html"
      content: "secure  page !!"
 
  - replace:
      path: "/etc/httpd/conf/httpd.conf"
      regexp: "AllowOverride None"
      replace: "AllowOverride AuthConfig"
 
  - copy:
      dest: "/var/www/html/.htaccess"
      src: ".htaccess"
 
  - package:
      name: "python36"
 
  - pip:
      name: "passlib"
 
  - htpasswd:
      path: "/etc/www.passwd"
      name: "kalpit"
      password: 'redhat'
 
  - service:
      name: "httpd"
      state: restarted
 
 
